# version 제거 (obsolete 경고 해결)

services:
  # Load Balancer (스위치 역할)
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"      # 80 대신 8080 사용
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green
    networks:
      - blue-green-network

  # Blue 환경 (첫 번째 서버)
  blue:
    image: blue-green-demo:v1  # 로컬에 빌드된 이미지 사용
    pull_policy: never          # 로컬 이미지만 사용 (Docker Hub에서 다운로드 안 함)
    environment:
      - APP_VERSION=1.0
      - APP_ENVIRONMENT=blue
    ports:
      - "8081:8080"  # 직접 접속용
    networks:
      - blue-green-network

  # Green 환경 (두 번째 서버)
  green:
    image: blue-green-demo:v1  # 같은 이미지 사용
    pull_policy: never          # 로컬 이미지만 사용
    environment:
      - APP_VERSION=2.0
      - APP_ENVIRONMENT=green
    ports:
      - "8082:8080"  # 직접 접속용
    networks:
      - blue-green-network

networks:
  blue-green-network:
    driver: bridge